"""Create flatened table

Revision ID: 970fb5810ea7
Revises: 
Create Date: 2025-12-05 21:47:31.218382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970fb5810ea7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_reviews_flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.TEXT(), nullable=False),
    sa.Column('user_email', sa.TEXT(), nullable=False),
    sa.Column('book_title', sa.TEXT(), nullable=False),
    sa.Column('book_isbn', sa.TEXT(), nullable=True),
    sa.Column('author_name', sa.TEXT(), nullable=False),
    sa.Column('author_country', sa.TEXT(), nullable=True),
    sa.Column('genre_name', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('review_date', sa.DATE(), nullable=False),
    sa.CheckConstraint("user_email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='checkue15'),
    sa.CheckConstraint('book_isbn IS NULL OR char_length(book_isbn) IN (10, 13)', name='checkbi15'),
    sa.CheckConstraint('rating > 0 and rating < 6', name='checkra15'),
    sa.CheckConstraint('review_date <= CURRENT_DATE', name='checkrd15'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_reviews_flat_id'), 'book_reviews_flat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_reviews_flat_id'), table_name='book_reviews_flat')
    op.drop_table('book_reviews_flat')
    # ### end Alembic commands ###
