"""create BCNF tables

Revision ID: fd8e6c8dad22
Revises: 52ed8da2aab8
Create Date: 2025-12-06 15:58:23.865919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8e6c8dad22'
down_revision: Union[str, Sequence[str], None] = '52ed8da2aab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.TEXT(), nullable=True),
    sa.Column('book_title', sa.TEXT(), nullable=False),
    sa.Column('author_name', sa.TEXT(), nullable=False),
    sa.Column('genre_name', sa.TEXT(), nullable=True),
    sa.CheckConstraint('book_isbn IS NULL OR char_length(book_isbn) IN (10, 13)', name='checkbi_books_15'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_id_fill70', 'books', ['id'], unique=False, postgresql_with={'fillfactor': 70})
    op.create_table('users',
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.TEXT(), nullable=False),
    sa.CheckConstraint("user_email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='checkue_users_15'),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_index('ix_user_email_fill70', 'users', ['user_email'], unique=False, postgresql_with={'fillfactor': 70})
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_email', sa.TEXT(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('review_date', sa.DATE(), nullable=False),
    sa.CheckConstraint('rating > 0 and rating < 6', name='checkra_reviews_15'),
    sa.CheckConstraint('review_date <= CURRENT_DATE', name='checkrd_reviews_15'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_email'], ['users.user_email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_id_fill70', 'reviews', ['id'], unique=False, postgresql_with={'fillfactor': 70})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_id_fill70', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_user_email_fill70', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_book_id_fill70', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
